export const Posts = [
    {
      id: 1,
      title: 'Healthy Breakfast Ideas',
      description: 'Start your day with these nutritious and delicious breakfast options.',
      image: 'https://i.pinimg.com/474x/24/2d/b4/242db4f6157c7c304b4391bbdf041f7a.jpg',
      content: [
        'Breakfast is the most important meal of the day. Here are some healthy ideas to kickstart your morning:',
        '1. **Oatmeal with Fruits**: A bowl of oatmeal topped with fresh fruits like bananas, berries, and a drizzle of honey.',
        '2. **Avocado Toast**: Whole-grain toast topped with mashed avocado, a sprinkle of salt, and a dash of chili flakes.',
        '3. **Smoothie Bowl**: Blend your favorite fruits with yogurt and top with granola and nuts for a refreshing breakfast.',
        '4. **Eggs and Veggies**: Scrambled eggs with spinach, tomatoes, and a slice of whole-grain bread.',
        '5. **Greek Yogurt Parfait**: Layer Greek yogurt with granola, nuts, and fresh fruits for a protein-packed breakfast.',
        '6. **Chia Pudding**: Mix chia seeds with almond milk and let it sit overnight. Top with fruits and nuts in the morning.',
      ],
    },
    {
      id: 2,
      title: 'Top 10 Superfoods',
      description: 'Discover the top superfoods that can boost your health and energy levels.',
      image: 'https://i.pinimg.com/474x/f1/69/f7/f169f7b307964d152a85c6855654b902.jpg',
      content: [
        'Superfoods are nutrient-rich foods that provide numerous health benefits. Here are the top 10 superfoods you should include in your diet:',
        '1. **Blueberries**: Packed with antioxidants and vitamins.',
        '2. **Kale**: A leafy green vegetable rich in iron and calcium.',
        '3. **Quinoa**: A protein-rich grain that is gluten-free.',
        '4. **Salmon**: High in omega-3 fatty acids, great for heart health.',
        '5. **Avocado**: Loaded with healthy fats and fiber.',
        '6. **Chia Seeds**: A great source of omega-3s and fiber.',
        '7. **Sweet Potatoes**: Rich in vitamins A and C.',
        '8. **Almonds**: A healthy snack full of protein and healthy fats.',
        '9. **Greek Yogurt**: High in protein and probiotics.',
        '10. **Green Tea**: Known for its antioxidants and metabolism-boosting properties.',
        '11. **Turmeric**: Contains curcumin, which has anti-inflammatory properties.',
        '12. **Spinach**: Rich in iron, calcium, and vitamins A and C.',
      ],
    },
    {
      id: 3,
      title: 'Meal Prep Tips',
      description: 'Learn how to efficiently meal prep for the week to maintain a healthy diet.',
      image: 'https://i.pinimg.com/474x/50/9e/10/509e109e05afe9668dc6e480c2073e75.jpg',
      content: [
        'Meal prepping can save you time and help you stick to a healthy diet. Here are some tips to get started:',
        '1. **Plan Your Meals**: Decide what you want to eat for the week and create a shopping list.',
        '2. **Cook in Batches**: Prepare large quantities of staple foods like rice, quinoa, and roasted vegetables.',
        '3. **Use Containers**: Invest in good-quality containers to store your meals.',
        '4. **Keep It Simple**: Stick to recipes with minimal ingredients to save time.',
        '5. **Prep Snacks**: Cut up fruits and veggies or portion out nuts for easy snacks.',
        '6. **Label Everything**: Use labels to keep track of when you prepared each meal.',
        '7. **Freeze Meals**: Prepare freezer-friendly meals for busy days.',
        '8. **Use a Slow Cooker**: Save time by cooking meals overnight or while you’re at work.',
      ],
    },
    {
      id: 4,
      title: 'Hydration Tips',
      description: 'Stay hydrated with these simple and effective tips for better health.',
      image: 'https://i.pinimg.com/474x/e4/07/5e/e4075eb907b72b13c8a35192b12d58e0.jpg',
      content: [
        'Staying hydrated is essential for overall health. Here are some tips to help you drink more water:',
        '1. **Carry a Water Bottle**: Always have a reusable water bottle with you.',
        '2. **Set Reminders**: Use your phone to remind you to drink water throughout the day.',
        '3. **Infuse Your Water**: Add fruits like lemon, cucumber, or berries for flavor.',
        '4. **Eat Water-Rich Foods**: Include foods like watermelon, cucumbers, and oranges in your diet.',
        '5. **Track Your Intake**: Use an app or journal to track how much water you drink daily.',
        '6. **Drink Herbal Tea**: Herbal teas are a great way to stay hydrated without caffeine.',
        '7. **Start Your Day with Water**: Drink a glass of water as soon as you wake up.',
      ],
    },
    {
      id: 5,
      title: 'Mindful Eating',
      description: 'Learn the art of mindful eating to improve your relationship with food.',
      image: 'https://i.pinimg.com/474x/5a/14/24/5a142462250722495a8109a7632d5577.jpg',
      content: [
        'Mindful eating is about being present while you eat and paying attention to your body’s hunger and fullness cues. Here’s how to practice it:',
        '1. **Eat Slowly**: Take your time to chew and savor each bite.',
        '2. **Avoid Distractions**: Turn off the TV and put away your phone while eating.',
        '3. **Listen to Your Body**: Eat when you’re hungry and stop when you’re full.',
        '4. **Appreciate Your Food**: Take a moment to appreciate the colors, textures, and flavors of your meal.',
        '5. **Portion Control**: Serve yourself smaller portions to avoid overeating.',
        '6. **Practice Gratitude**: Reflect on where your food comes from and the effort that went into preparing it.',
      ],
    },
    {
      id: 6,
      title: 'Benefits of Yoga',
      description: 'Discover how yoga can improve your physical and mental well-being.',
      image: 'https://i.pinimg.com/474x/01/58/f0/0158f05b96c911152c01646e4d185e70.jpg',
      content: [
        'Yoga is a holistic practice that benefits both the body and mind. Here are some of its key benefits:',
        '1. **Improves Flexibility**: Regular practice can increase your range of motion.',
        '2. **Reduces Stress**: Yoga promotes relaxation and reduces cortisol levels.',
        '3. **Boosts Strength**: Many poses require you to support your body weight, building muscle strength.',
        '4. **Enhances Mental Clarity**: Yoga encourages mindfulness and focus.',
        '5. **Improves Posture**: Strengthens core muscles and aligns the spine.',
        '6. **Promotes Better Sleep**: Relaxation techniques in yoga can help you sleep better.',
      ],
    },
    {
      id: 7,
      title: 'Healthy Snacks',
      description: 'Explore delicious and healthy snack options to keep you energized throughout the day.',
      image: 'https://i.pinimg.com/474x/b9/2a/88/b92a88d07477912bd096351a3ada0ff0.jpg',
      content: [
        'Healthy snacks can keep you energized and prevent overeating during meals. Here are some great options:',
        '1. **Fruit and Nut Butter**: Apple slices with almond butter.',
        '2. **Trail Mix**: A mix of nuts, seeds, and dried fruits.',
        '3. **Veggie Sticks with Hummus**: Carrot and cucumber sticks with a side of hummus.',
        '4. **Greek Yogurt with Honey**: A protein-rich snack with a touch of sweetness.',
        '5. **Dark Chocolate**: A small piece of dark chocolate for a healthy treat.',
        '6. **Rice Cakes with Avocado**: A light and satisfying snack.',
      ],
    },
  ];





  export const WorkoutPlans = [
    {
        id: 1,
        title: 'Beginner Full-Body Workout',
        description: 'A simple yet effective workout plan for beginners.',
        image: 'https://i.pinimg.com/474x/62/27/9c/62279c12b7680f3ef9638f95b3a6a50e.jpg',
        content: [
          'This plan is perfect for those new to fitness. It focuses on building strength and endurance.',
          '1. **Warm-Up**: 5-10 minutes of light cardio (e.g., jogging or jumping jacks).',
          '2. **Squats**: 3 sets of 12 reps.',
          '3. **Push-Ups**: 3 sets of 10 reps.',
          '4. **Lunges**: 3 sets of 10 reps per leg.',
          '5. **Plank**: Hold for 30 seconds, 3 sets.',
          '6. **Cool Down**: Stretch all major muscle groups.',
        ],
      },
      {
        id: 2,
        title: 'Advanced HIIT Workout',
        description: 'A high-intensity interval training plan for advanced fitness enthusiasts.',
        image: 'https://i.pinimg.com/474x/e5/ff/a2/e5ffa2545f0bae5e913e08e41cb3bbe2.jpg',
        content: [
          'This plan is designed to push your limits and burn maximum calories.',
          '1. **Warm-Up**: 5-10 minutes of dynamic stretching.',
          '2. **Burpees**: 4 sets of 15 reps.',
          '3. **Mountain Climbers**: 4 sets of 20 reps.',
          '4. **Jump Squats**: 4 sets of 12 reps.',
          '5. **Push-Up to Side Plank**: 4 sets of 10 reps per side.',
          '6. **Cool Down**: Stretch and hydrate.',
        ],
      },
      {
        id: 3,
        title: 'Yoga for Flexibility',
        description: 'Improve your flexibility and mindfulness with this yoga plan.',
        image: 'https://i.pinimg.com/474x/d7/c8/23/d7c82322c576c4638b694b3ae88149cf.jpg',
        content: [
          'This plan focuses on stretching and relaxation.',
          '1. **Child Pose**: Hold for 1 minute.',
          '2. **Downward Dog**: Hold for 1 minute.',
          '3. **Warrior II**: Hold for 30 seconds per side.',
          '4. **Tree Pose**: Hold for 30 seconds per side.',
          '5. **Seated Forward Bend**: Hold for 1 minute.',
          '6. **Savasana**: Relax for 5 minutes.',
        ],
      },
      {
        id: 4,
        title: 'Strength Training for Muscle Gain',
        description: 'Build muscle and strength with this weightlifting plan.',
        image: 'https://i.pinimg.com/474x/07/20/49/0720493c2100dcf27516f54d09e2fb39.jpg',
        content: [
          'This plan is ideal for those looking to gain muscle mass.',
          '1. **Bench Press**: 4 sets of 8 reps.',
          '2. **Deadlifts**: 4 sets of 6 reps.',
          '3. **Pull-Ups**: 3 sets of 10 reps.',
          '4. **Barbell Squats**: 4 sets of 8 reps.',
          '5. **Dumbbell Rows**: 3 sets of 10 reps per side.',
          '6. **Cool Down**: Stretch and hydrate.',
        ],
      },
  ];